-- Clean and Upload French Learning Content from Markdown
-- Based on french_notes_Version3.md - Beginner Level Content
-- Uses correct pronunciation_words table structure and existing content schema

-- ==============================================
-- STEP 1: CLEAN EXISTING DATA
-- ==============================================

-- Clear in reverse dependency order to avoid foreign key issues
DELETE FROM vocabulary_tags;
DELETE FROM lesson_tags;
DELETE FROM lesson_grammar;
DELETE FROM lesson_vocabulary;
DELETE FROM questions;
DELETE FROM pronunciation_words;
DELETE FROM lessons;
DELETE FROM grammar_rules;
DELETE FROM vocabulary;
DELETE FROM modules;

-- Reset sequences
SELECT setval('modules_id_seq', 1, false);
SELECT setval('vocabulary_id_seq', 1, false);
SELECT setval('grammar_rules_id_seq', 1, false);
SELECT setval('lessons_id_seq', 1, false);
SELECT setval('questions_id_seq', 1, false);

-- ==============================================
-- STEP 2: CREATE PRONUNCIATION_WORDS TABLE (if not exists)
-- ==============================================

CREATE TABLE IF NOT EXISTS pronunciation_words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  french TEXT NOT NULL,
  english TEXT NOT NULL,
  pronunciation TEXT,
  example TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ==============================================
-- STEP 3: INSERT MODULES FROM MARKDOWN (Beginner Level)
-- ==============================================

INSERT INTO modules (id, level_id, title, description, order_index) VALUES
-- Assuming level_id=1 exists for Beginner
(1, 1, 'Module I: Greetings (Les Salutations)', 'Learn fundamental greetings, formal vs informal language, and basic introductions', 1),
(2, 1, 'Module II: At the Restaurant (Au Restaurant)', 'Essential vocabulary and phrases for dining out, ordering food and drinks', 2),
(3, 1, 'Module III: Talking about Professions (Parler des Professions)', 'Learn to describe professions, nationalities, and daily routines', 3),
(4, 1, 'Module V: At the Discotheque (À la Discothèque)', 'Question formation, negation, and social conversation skills', 4);

-- Reset sequence
SELECT setval('modules_id_seq', 4, true);

-- ==============================================
-- STEP 4: INSERT VOCABULARY FROM MARKDOWN
-- ==============================================

INSERT INTO vocabulary (id, french_word, english_translation, pronunciation, example_sentence_fr, example_sentence_en, difficulty_level, category, word_type, gender) VALUES
-- Module I: Greetings vocabulary
(1, 'Bonjour', 'Good day, Hello', 'bon-zhoor', 'Bonjour, comment allez-vous?', 'Hello, how are you?', 'beginner', 'Greetings', 'interjection', NULL),
(2, 'Salut', 'Hi, Bye (informal)', 'sa-loot', 'Salut, ça va?', 'Hi, how are you?', 'beginner', 'Greetings', 'interjection', NULL),
(3, 'Bonsoir', 'Good evening', 'bon-swahr', 'Bonsoir madame Martin.', 'Good evening Mrs. Martin.', 'beginner', 'Greetings', 'interjection', NULL),
(4, 'Bonne nuit', 'Good night', 'bun nwee', 'Bonne nuit et dormez bien.', 'Good night and sleep well.', 'beginner', 'Greetings', 'interjection', NULL),
(5, 'Au revoir', 'Goodbye', 'oh ruh-vwahr', 'Au revoir et à bientôt!', 'Goodbye and see you soon!', 'beginner', 'Greetings', 'interjection', NULL),
(6, 'À bientôt', 'See you soon', 'ah bee-an-toh', 'À bientôt mes amis!', 'See you soon my friends!', 'beginner', 'Greetings', 'interjection', NULL),
(7, 'Ça va', 'How are you / I''m okay', 'sa va', 'Ça va bien, merci.', 'I''m doing well, thank you.', 'beginner', 'Greetings', 'expression', NULL),
(8, 'vous', 'you (formal/plural)', 'voo', 'Comment vous appelez-vous?', 'What is your name?', 'beginner', 'Pronouns', 'pronoun', NULL),
(9, 'tu', 'you (informal)', 'tuu', 'Comment t''appelles-tu?', 'What is your name?', 'beginner', 'Pronouns', 'pronoun', NULL),
(10, 'un ami', 'a friend (male)', 'un na-mee', 'Il est mon ami.', 'He is my friend.', 'beginner', 'People', 'noun', 'masculine'),
(11, 'une amie', 'a friend (female)', 'une na-mee', 'Elle est mon amie.', 'She is my friend.', 'beginner', 'People', 'noun', 'feminine'),
(12, 'un homme', 'a man', 'un ohm', 'Cet homme est grand.', 'This man is tall.', 'beginner', 'People', 'noun', 'masculine'),
(13, 'une femme', 'a woman', 'une fam', 'Cette femme est intelligente.', 'This woman is intelligent.', 'beginner', 'People', 'noun', 'feminine'),
(14, 'Monsieur', 'Sir, Mr.', 'muh-syur', 'Bonjour Monsieur Dupont.', 'Hello Mr. Dupont.', 'beginner', 'Titles', 'noun', 'masculine'),
(15, 'Madame', 'Ma''am, Mrs.', 'ma-dam', 'Bonsoir Madame Martin.', 'Good evening Mrs. Martin.', 'beginner', 'Titles', 'noun', 'feminine'),
(16, 'oui', 'yes', 'wee', 'Oui, c''est correct.', 'Yes, that''s correct.', 'beginner', 'Basic', 'adverb', NULL),
(17, 'non', 'no', 'non', 'Non, ce n''est pas vrai.', 'No, that''s not true.', 'beginner', 'Basic', 'adverb', NULL),
(18, 'merci', 'thank you', 'mer-see', 'Merci beaucoup!', 'Thank you very much!', 'beginner', 'Greetings', 'interjection', NULL),
(19, 's''il vous plaît', 'please (formal)', 'seel voo pleh', 'Un café, s''il vous plaît.', 'A coffee, please.', 'beginner', 'Greetings', 'expression', NULL),
(20, 's''il te plaît', 'please (informal)', 'seel tuh pleh', 'Aide-moi, s''il te plaît.', 'Help me, please.', 'beginner', 'Greetings', 'expression', NULL),
(21, 'enchanté', 'pleased to meet you (male)', 'on-shon-tay', 'Enchanté de vous rencontrer.', 'Pleased to meet you.', 'beginner', 'Greetings', 'adjective', NULL),
(22, 'enchantée', 'pleased to meet you (female)', 'on-shon-tay', 'Enchantée de faire votre connaissance.', 'Pleased to make your acquaintance.', 'beginner', 'Greetings', 'adjective', NULL),

-- Essential être conjugations
(23, 'je suis', 'I am', 'zhuh swee', 'Je suis français.', 'I am French.', 'beginner', 'Verbs', 'verb', NULL),
(24, 'tu es', 'you are (informal)', 'tuu eh', 'Tu es étudiant?', 'Are you a student?', 'beginner', 'Verbs', 'verb', NULL),
(25, 'il est', 'he is', 'eel eh', 'Il est professeur.', 'He is a teacher.', 'beginner', 'Verbs', 'verb', NULL),
(26, 'elle est', 'she is', 'ell eh', 'Elle est médecin.', 'She is a doctor.', 'beginner', 'Verbs', 'verb', NULL),
(27, 'nous sommes', 'we are', 'noo som', 'Nous sommes amis.', 'We are friends.', 'beginner', 'Verbs', 'verb', NULL),
(28, 'vous êtes', 'you are (formal/plural)', 'voo zet', 'Vous êtes le professeur.', 'You are the teacher.', 'beginner', 'Verbs', 'verb', NULL),
(29, 'ils sont', 'they are (masculine)', 'eel son', 'Ils sont étudiants.', 'They are students.', 'beginner', 'Verbs', 'verb', NULL),
(30, 'elles sont', 'they are (feminine)', 'ell son', 'Elles sont françaises.', 'They are French.', 'beginner', 'Verbs', 'verb', NULL);

-- Reset sequence
SELECT setval('vocabulary_id_seq', 30, true);

-- ==============================================
-- STEP 5: INSERT GRAMMAR RULES FROM MARKDOWN  
-- ==============================================

INSERT INTO grammar_rules (id, title, explanation, examples, difficulty_level, category, order_index) VALUES
(1, 'Formal vs. Informal: vous and tu', 'The pronoun you choose shows respect and your relationship with the person. Use tu with friends, family, children, peers. Use vous with strangers, older people, authority figures, in professional settings.',
 '[{"french": "Comment vous appelez-vous?", "english": "What is your name? (formal)"}, {"french": "Comment t''appelles-tu?", "english": "What is your name? (informal)"}, {"french": "Vous êtes le professeur", "english": "You are the teacher"}]',
 'beginner', 'pronouns', 1),

(2, 'The Verb être (to be)', 'The most fundamental irregular verb in French: je suis, tu es, il/elle est, nous sommes, vous êtes, ils/elles sont',
 '[{"french": "Je suis français", "english": "I am French"}, {"french": "Tu es étudiant", "english": "You are a student"}, {"french": "Ils sont étudiants", "english": "They are students"}]',
 'beginner', 'verbs', 2),

(3, 'Reflexive Verb s''appeler (to be called)', 'Used to state names. Reflexive verbs reflect the action back onto the subject using reflexive pronouns (me, te, se, nous, vous, se).',
 '[{"french": "Je m''appelle Marie", "english": "My name is Marie"}, {"french": "Comment vous appelez-vous?", "english": "What is your name?"}, {"french": "Elles s''appellent Sophie et Claire", "english": "Their names are Sophie and Claire"}]',
 'beginner', 'verbs', 3),

(4, 'Greetings Throughout the Day', 'Different greetings are appropriate for different times: Bonjour (morning to late afternoon), Bonsoir (evening greeting), Bonne nuit (only when going to bed).',
 '[{"french": "Bonjour madame", "english": "Good morning/day, ma''am"}, {"french": "Bonsoir monsieur", "english": "Good evening, sir"}, {"french": "Bonne nuit et dormez bien", "english": "Good night and sleep well"}]',
 'beginner', 'expressions', 4);

-- Reset sequence  
SELECT setval('grammar_rules_id_seq', 4, true);

-- ==============================================
-- STEP 6: INSERT LESSONS FROM MARKDOWN
-- ==============================================

INSERT INTO lessons (id, module_id, title, description, content, lesson_type, order_index, difficulty_level, estimated_time_minutes) VALUES
-- Module I: Greetings lessons
(1, 1, 'Formal vs. Informal: vous and tu', 'Master the crucial distinction between formal and informal address in French', 
 '{"introduction": "Learn when to use vous vs tu", "key_concepts": ["formal situations", "informal relationships", "verb conjugations"], "cultural_notes": ["When in doubt, use vous"]}', 
 'grammar', 1, 'beginner', 20),

(2, 1, 'Greetings Throughout the Day', 'Learn appropriate greetings for different times and situations', 
 '{"introduction": "Time-appropriate greetings", "vocabulary": ["bonjour", "bonsoir", "salut", "bonne nuit"], "usage_rules": ["morning vs evening", "formal vs informal"]}', 
 'vocabulary', 2, 'beginner', 15),

(3, 1, 'Introductions and Names', 'How to introduce yourself and ask for names in French', 
 '{"introduction": "Personal introductions", "key_phrases": ["Comment vous appelez-vous?", "Je m''appelle", "Enchanté/Enchantée"], "grammar_focus": "Reflexive verbs"}', 
 'conversation', 3, 'beginner', 20),

(4, 1, 'The Verb être (to be)', 'Master the fundamental irregular verb être', 
 '{"introduction": "Essential verb conjugations", "conjugations": ["je suis", "tu es", "il/elle est", "nous sommes", "vous êtes", "ils/elles sont"], "usage": "identity and description"}', 
 'grammar', 4, 'beginner', 25);

-- Reset sequence
SELECT setval('lessons_id_seq', 4, true);

-- ==============================================
-- STEP 7: INSERT PRONUNCIATION WORDS FROM MARKDOWN
-- ==============================================

INSERT INTO pronunciation_words (french, english, pronunciation, example) VALUES
-- Core greetings pronunciations
('bonjour', 'hello, good morning', 'bon-zhoor', 'Bonjour, comment allez-vous?'),
('bonsoir', 'good evening', 'bon-swahr', 'Bonsoir madame Martin.'),
('salut', 'hi, bye (informal)', 'sa-loot', 'Salut, ça va?'),
('au revoir', 'goodbye', 'oh ruh-vwahr', 'Au revoir et à bientôt!'),
('à bientôt', 'see you soon', 'ah bee-an-toh', 'À bientôt mes amis!'),
('merci', 'thank you', 'mer-see', 'Merci beaucoup!'),
('ça va', 'how are you / I''m okay', 'sa va', 'Ça va bien, merci.'),

-- Formal vs informal pronouns
('vous', 'you (formal/plural)', 'voo', 'Comment vous appelez-vous?'),
('tu', 'you (informal)', 'tuu', 'Comment t''appelles-tu?'),

-- Question words and expressions
('comment', 'how', 'kom-mohn', 'Comment vous appelez-vous?'),
('s''appeler', 'to be called', 'sa-pell-ay', 'Je m''appelle Marie'),

-- Essential être conjugations
('je suis', 'I am', 'zhuh swee', 'Je suis français.'),
('tu es', 'you are (informal)', 'tuu eh', 'Tu es étudiant?'),
('il est', 'he is', 'eel eh', 'Il est professeur.'),
('elle est', 'she is', 'ell eh', 'Elle est médecin.'),
('nous sommes', 'we are', 'noo som', 'Nous sommes amis.'),
('vous êtes', 'you are (formal)', 'voo zet', 'Vous êtes le professeur.'),
('ils sont', 'they are (masculine)', 'eel son', 'Ils sont étudiants.'),
('elles sont', 'they are (feminine)', 'ell son', 'Elles sont françaises.'),

-- People and titles
('monsieur', 'sir, mister', 'muh-syur', 'Bonjour Monsieur Dupont.'),
('madame', 'madam, mrs', 'ma-dam', 'Bonsoir Madame Martin.'),
('un ami', 'a friend (male)', 'un na-mee', 'Il est mon ami.'),
('une amie', 'a friend (female)', 'une na-mee', 'Elle est mon amie.'),
('enchanté', 'pleased to meet you (male)', 'on-shon-tay', 'Enchanté de vous rencontrer.'),
('enchantée', 'pleased to meet you (female)', 'on-shon-tay', 'Enchantée de faire votre connaissance.');

-- ==============================================
-- STEP 8: INSERT QUESTIONS FROM MARKDOWN CONTENT
-- ==============================================

INSERT INTO questions (id, lesson_id, question_text, question_type, options, correct_answer, explanation, points, difficulty_level, order_index) VALUES
-- Lesson 1: Formal vs Informal questions
(1, 1, 'When should you use "vous" instead of "tu"?', 'multiple_choice', 
 '["With close friends only", "With strangers or in formal situations", "Only with children", "Never, always use tu"]',
 'With strangers or in formal situations', 'Vous is used for formal situations, with strangers, older people, and authority figures', 10, 'beginner', 1),

(2, 1, 'Complete the formal question: "Comment ___ appelez-vous?"', 'fill_blank', 
 '["vous", "tu", "il", "elle"]',
 'vous', 'Use "vous" for the formal way to ask someone''s name', 10, 'beginner', 2),

-- Lesson 2: Greetings questions
(3, 2, 'What is the appropriate greeting for the evening?', 'multiple_choice',
 '["Bonjour", "Salut", "Bonsoir", "Bonne nuit"]',
 'Bonsoir', 'Bonsoir is used to greet people in the evening, typically after 6 PM', 10, 'beginner', 1),

(4, 2, 'Which greeting can be used for both "hello" and "goodbye"?', 'multiple_choice',
 '["Bonjour", "Au revoir", "Salut", "Bonsoir"]',
 'Salut', 'Salut is informal and can mean both hi and bye', 10, 'beginner', 2),

-- Lesson 3: Introductions questions  
(5, 3, 'How do you say "My name is..." in French?', 'multiple_choice',
 '["Mon nom est", "Je m''appelle", "Je suis nom", "Ma nom c''est"]',
 'Je m''appelle', 'Je m''appelle is the standard way to introduce your name', 15, 'beginner', 1),

(6, 3, 'What do you say when meeting someone for the first time (if you''re male)?', 'multiple_choice',
 '["Bonjour", "Salut", "Enchanté", "Merci"]',
 'Enchanté', 'Enchanté means "pleased to meet you" (said by males)', 10, 'beginner', 2),

-- Lesson 4: Être verb questions
(7, 4, 'Complete: "Je ___ français" (I am French)', 'fill_blank',
 '["suis", "es", "est", "êtes"]',
 'suis', 'Je suis is the correct conjugation of être with je', 15, 'beginner', 1),

(8, 4, 'What is the correct form: "Vous ___ le professeur"', 'fill_blank',
 '["suis", "es", "est", "êtes"]',
 'êtes', 'Vous êtes is the correct conjugation of être with vous', 15, 'beginner', 2);

-- Reset sequence
SELECT setval('questions_id_seq', 8, true);

-- ==============================================
-- STEP 9: LINK VOCABULARY TO LESSONS  
-- ==============================================

INSERT INTO lesson_vocabulary (lesson_id, vocabulary_id, is_primary) VALUES
-- Lesson 1: Formal vs Informal - key pronouns
(1, 8, true),   -- vous
(1, 9, true),   -- tu  
(1, 28, true),  -- vous êtes
(1, 24, true),  -- tu es

-- Lesson 2: Greetings - core greetings
(2, 1, true),   -- Bonjour
(2, 2, true),   -- Salut
(2, 3, true),   -- Bonsoir  
(2, 4, true),   -- Bonne nuit
(2, 5, true),   -- Au revoir
(2, 6, true),   -- À bientôt
(2, 7, true),   -- Ça va

-- Lesson 3: Introductions - introduction vocabulary
(3, 21, true),  -- enchanté
(3, 22, true),  -- enchantée
(3, 14, true),  -- Monsieur
(3, 15, true),  -- Madame
(3, 10, true),  -- un ami
(3, 11, true),  -- une amie

-- Lesson 4: Être verb - all conjugations
(4, 23, true),  -- je suis
(4, 24, true),  -- tu es
(4, 25, true),  -- il est
(4, 26, true),  -- elle est
(4, 27, true),  -- nous sommes
(4, 28, true),  -- vous êtes
(4, 29, true),  -- ils sont
(4, 30, true);  -- elles sont

-- ==============================================
-- STEP 10: LINK GRAMMAR TO LESSONS
-- ==============================================

INSERT INTO lesson_grammar (lesson_id, grammar_rule_id, is_primary) VALUES
-- Link grammar rules to appropriate lessons
(1, 1, true),   -- Formal vs Informal grammar
(2, 4, true),   -- Greetings throughout the day
(3, 3, true),   -- Reflexive verb s'appeler
(4, 2, true);   -- The verb être

-- ==============================================
-- VERIFICATION AND SUMMARY
-- ==============================================

-- Display summary of inserted content
SELECT 'Content Upload Summary:' as status;
SELECT 'Modules created:' as type, COUNT(*) as count FROM modules;
SELECT 'Vocabulary items:' as type, COUNT(*) as count FROM vocabulary;
SELECT 'Grammar rules:' as type, COUNT(*) as count FROM grammar_rules;
SELECT 'Lessons created:' as type, COUNT(*) as count FROM lessons;
SELECT 'Pronunciation words:' as type, COUNT(*) as count FROM pronunciation_words;
SELECT 'Questions created:' as type, COUNT(*) as count FROM questions;
SELECT 'Lesson-vocabulary links:' as type, COUNT(*) as count FROM lesson_vocabulary;
SELECT 'Lesson-grammar links:' as type, COUNT(*) as count FROM lesson_grammar;

SELECT '✅ French learning content from markdown has been successfully uploaded!' as final_message;
