-- Clean and Upload French Learning Content - Direct Supabase Execution
-- Based on french_notes_Version3.md - Beginner Level Content
-- Run this directly in Supabase SQL Editor

-- ==============================================
-- STEP 1: CLEAN EXISTING DATA
-- ==============================================

-- Clear data in reverse dependency order
DELETE FROM vocabulary_tags WHERE id > 0;
DELETE FROM lesson_tags WHERE id > 0;
DELETE FROM lesson_grammar WHERE id > 0;
DELETE FROM lesson_vocabulary WHERE id > 0;
DELETE FROM questions WHERE id > 0;
DELETE FROM pronunciation_words WHERE id > 0;
DELETE FROM lessons WHERE id > 0;
DELETE FROM grammar_rules WHERE id > 0;
DELETE FROM vocabulary WHERE id > 0;
DELETE FROM modules WHERE id > 0;

-- Reset sequences to start fresh
ALTER SEQUENCE IF EXISTS modules_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS vocabulary_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS grammar_rules_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS lessons_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS questions_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS pronunciation_words_id_seq RESTART WITH 1;

-- ==============================================
-- STEP 2: CREATE PRONUNCIATION WORDS TABLE
-- ==============================================

CREATE TABLE IF NOT EXISTS pronunciation_words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  french TEXT NOT NULL,
  english TEXT NOT NULL,
  pronunciation TEXT,
  example TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ==============================================
-- STEP 3: INSERT MODULES (Beginner Level from Markdown)
-- ==============================================

INSERT INTO modules (level_id, title, description, order_index) VALUES
-- Assuming level_id=1 exists for Beginner
(1, 'Module I: Greetings (Les Salutations)', 'Learn fundamental greetings, formal vs informal language, and basic introductions', 1),
(1, 'Module II: At the Restaurant (Au Restaurant)', 'Essential vocabulary and phrases for dining out, ordering food and drinks', 2),
(1, 'Module III: Talking about Professions (Parler des Professions)', 'Learn to describe professions, nationalities, and daily routines', 3),
(1, 'Module IV: At the Discotheque (À la Discothèque)', 'Question formation, negation, and social conversation skills', 4);

-- ==============================================
-- STEP 4: INSERT VOCABULARY FROM MARKDOWN
-- ==============================================

INSERT INTO vocabulary (french_word, english_translation, pronunciation, example_sentence_fr, example_sentence_en, difficulty_level, category, word_type, gender) VALUES
-- Module I: Greetings vocabulary from markdown
('bonjour', 'good day, hello', 'bon-zhoor', 'Bonjour, comment allez-vous?', 'Hello, how are you?', 'beginner', 'greetings', 'interjection', NULL),
('salut', 'hi, bye (informal)', 'sa-loot', 'Salut, ça va?', 'Hi, how are you?', 'beginner', 'greetings', 'interjection', NULL),
('bonsoir', 'good evening', 'bon-swahr', 'Bonsoir madame Martin.', 'Good evening Mrs. Martin.', 'beginner', 'greetings', 'interjection', NULL),
('bonne nuit', 'good night', 'bun nwee', 'Bonne nuit et dormez bien.', 'Good night and sleep well.', 'beginner', 'greetings', 'interjection', NULL),
('au revoir', 'goodbye', 'oh ruh-vwahr', 'Au revoir et à bientôt!', 'Goodbye and see you soon!', 'beginner', 'greetings', 'interjection', NULL),
('à bientôt', 'see you soon', 'ah bee-an-toh', 'À bientôt mes amis!', 'See you soon my friends!', 'beginner', 'greetings', 'interjection', NULL),
('ça va', 'how are you / I''m okay', 'sa va', 'Ça va bien, merci.', 'I''m doing well, thank you.', 'beginner', 'greetings', 'interjection', NULL),

-- Formal vs informal pronouns
('vous', 'you (formal/plural)', 'voo', 'Comment vous appelez-vous?', 'What is your name?', 'beginner', 'pronouns', 'noun', NULL),
('tu', 'you (informal)', 'tuu', 'Comment t''appelles-tu?', 'What is your name?', 'beginner', 'pronouns', 'noun', NULL),

-- People and relationships
('un ami', 'a friend (male)', 'un na-mee', 'Il est mon ami.', 'He is my friend.', 'beginner', 'people', 'noun', 'masculine'),
('une amie', 'a friend (female)', 'une na-mee', 'Elle est mon amie.', 'She is my friend.', 'beginner', 'people', 'noun', 'feminine'),
('un homme', 'a man', 'un ohm', 'Cet homme est grand.', 'This man is tall.', 'beginner', 'people', 'noun', 'masculine'),
('une femme', 'a woman', 'une fam', 'Cette femme est intelligente.', 'This woman is intelligent.', 'beginner', 'people', 'noun', 'feminine'),
('un garçon', 'a boy', 'un gar-son', 'Le garçon joue au football.', 'The boy plays football.', 'beginner', 'people', 'noun', 'masculine'),
('une fille', 'a girl', 'une fee', 'La fille lit un livre.', 'The girl reads a book.', 'beginner', 'people', 'noun', 'feminine'),

-- Titles and courtesy
('monsieur', 'sir, mister', 'muh-syur', 'Bonjour Monsieur Dupont.', 'Hello Mr. Dupont.', 'beginner', 'titles', 'noun', 'masculine'),
('madame', 'ma''am, mrs', 'ma-dam', 'Bonsoir Madame Martin.', 'Good evening Mrs. Martin.', 'beginner', 'titles', 'noun', 'feminine'),
('mademoiselle', 'miss', 'mad-mwa-zel', 'Bonjour Mademoiselle Sophie.', 'Hello Miss Sophie.', 'beginner', 'titles', 'noun', 'feminine'),

-- Basic responses
('oui', 'yes', 'wee', 'Oui, c''est correct.', 'Yes, that''s correct.', 'beginner', 'basic', 'adverb', NULL),
('non', 'no', 'non', 'Non, ce n''est pas vrai.', 'No, that''s not true.', 'beginner', 'basic', 'adverb', NULL),
('merci', 'thank you', 'mer-see', 'Merci beaucoup!', 'Thank you very much!', 'beginner', 'greetings', 'interjection', NULL),
('s''il vous plaît', 'please (formal)', 'seel voo pleh', 'Un café, s''il vous plaît.', 'A coffee, please.', 'beginner', 'courtesy', 'interjection', NULL),
('s''il te plaît', 'please (informal)', 'seel tuh pleh', 'Aide-moi, s''il te plaît.', 'Help me, please.', 'beginner', 'courtesy', 'interjection', NULL),

-- Meeting people
('enchanté', 'pleased to meet you (male)', 'on-shon-tay', 'Enchanté de vous rencontrer.', 'Pleased to meet you.', 'beginner', 'introductions', 'adjective', NULL),
('enchantée', 'pleased to meet you (female)', 'on-shon-tay', 'Enchantée de faire votre connaissance.', 'Pleased to make your acquaintance.', 'beginner', 'introductions', 'adjective', NULL),

-- Essential être conjugations
('je suis', 'I am', 'zhuh swee', 'Je suis français.', 'I am French.', 'beginner', 'verbs', 'verb', NULL),
('tu es', 'you are (informal)', 'tuu eh', 'Tu es étudiant?', 'Are you a student?', 'beginner', 'verbs', 'verb', NULL),
('il est', 'he is', 'eel eh', 'Il est professeur.', 'He is a teacher.', 'beginner', 'verbs', 'verb', NULL),
('elle est', 'she is', 'ell eh', 'Elle est médecin.', 'She is a doctor.', 'beginner', 'verbs', 'verb', NULL),
('nous sommes', 'we are', 'noo som', 'Nous sommes amis.', 'We are friends.', 'beginner', 'verbs', 'verb', NULL),
('vous êtes', 'you are (formal/plural)', 'voo zet', 'Vous êtes le professeur.', 'You are the teacher.', 'beginner', 'verbs', 'verb', NULL),
('ils sont', 'they are (masculine)', 'eel son', 'Ils sont étudiants.', 'They are students.', 'beginner', 'verbs', 'verb', NULL),
('elles sont', 'they are (feminine)', 'ell son', 'Elles sont françaises.', 'They are French.', 'beginner', 'verbs', 'verb', NULL),

-- Question words and common adverbs
('comment', 'how', 'kom-mohn', 'Comment vous appelez-vous?', 'What is your name?', 'beginner', 'questions', 'adverb', NULL),
('où', 'where', 'oo', 'Où habitez-vous?', 'Where do you live?', 'beginner', 'questions', 'adverb', NULL),
('quand', 'when', 'kohn', 'Quand arrivez-vous?', 'When do you arrive?', 'beginner', 'questions', 'adverb', NULL),
('pourquoi', 'why', 'poor-kwah', 'Pourquoi partez-vous?', 'Why are you leaving?', 'beginner', 'questions', 'adverb', NULL),
('pardon', 'excuse me, pardon', 'par-don', 'Pardon, où est la gare?', 'Excuse me, where is the station?', 'beginner', 'courtesy', 'interjection', NULL),
('excusez-moi', 'excuse me (formal)', 'ex-ku-zay mwah', 'Excusez-moi, pouvez-vous m''aider?', 'Excuse me, can you help me?', 'beginner', 'courtesy', 'interjection', NULL);

-- ==============================================
-- STEP 5: INSERT GRAMMAR RULES FROM MARKDOWN
-- ==============================================

INSERT INTO grammar_rules (title, explanation, examples, difficulty_level, category, order_index, created_at) VALUES
('Formal vs. Informal: vous and tu', 
 'The pronoun you choose shows respect and your relationship with the person. Use tu with friends, family, children, peers, and anyone who invites you to use it. Use vous with strangers, older people, authority figures (teachers, police), in professional settings, or when addressing a group. When in doubt, use vous - it is always safer and more polite.',
 '[{"french": "Comment vous appelez-vous?", "english": "What is your name? (formal)"}, {"french": "Comment t''appelles-tu?", "english": "What is your name? (informal)"}, {"french": "Vous êtes le professeur", "english": "You are the teacher"}, {"french": "Tu es mon ami", "english": "You are my friend"}]',
 'beginner', 'pronouns', 1, NOW()),

('The Verb être (to be)', 
 'The most fundamental irregular verb in French. Essential conjugations: je suis (I am), tu es (you are informal), il/elle est (he/she is), nous sommes (we are), vous êtes (you are formal/plural), ils/elles sont (they are). This verb is used for identity, description, location, and temporary states.',
 '[{"french": "Je suis français", "english": "I am French"}, {"french": "Tu es étudiant", "english": "You are a student"}, {"french": "Elle est professeur", "english": "She is a teacher"}, {"french": "Nous sommes amis", "english": "We are friends"}, {"french": "Ils sont étudiants", "english": "They are students"}]',
 'beginner', 'verbs', 2, NOW()),

('Reflexive Verb s''appeler (to be called)', 
 'Used to state names and introduce yourself. Reflexive verbs reflect the action back onto the subject using reflexive pronouns (me, te, se, nous, vous, se). Je m''appelle (my name is), tu t''appelles (your name is), il/elle s''appelle (his/her name is).',
 '[{"french": "Je m''appelle Marie", "english": "My name is Marie"}, {"french": "Comment vous appelez-vous?", "english": "What is your name? (formal)"}, {"french": "Comment tu t''appelles?", "english": "What is your name? (informal)"}, {"french": "Il s''appelle Pierre", "english": "His name is Pierre"}]',
 'beginner', 'verbs', 3, NOW()),

('Greetings Throughout the Day', 
 'Different greetings are appropriate for different times and situations. Bonjour (universal greeting from morning to late afternoon), Salut (informal hi/bye with people you would address with tu), Bonsoir (good evening greeting after 6 PM), Bonne nuit (only when someone is going to bed), Au revoir (standard goodbye), À bientôt (see you soon).',
 '[{"french": "Bonjour madame", "english": "Good morning/day, ma''am"}, {"french": "Salut les amis!", "english": "Hi friends!"}, {"french": "Bonsoir monsieur", "english": "Good evening, sir"}, {"french": "Bonne nuit et dormez bien", "english": "Good night and sleep well"}, {"french": "À bientôt!", "english": "See you soon!"}]',
 'beginner', 'expressions', 4, NOW()),

('Basic Question Formation', 
 'Three ways to ask questions in French: 1) Raise your voice at the end (Est-ce que tu vas bien?), 2) Use est-ce que + statement (Est-ce que vous parlez français?), 3) Formal inversion (Parlez-vous français?). Start with the first method as it''s most common in everyday speech.',
 '[{"french": "Tu vas bien?", "english": "Are you doing well?"}, {"french": "Est-ce que vous parlez français?", "english": "Do you speak French?"}, {"french": "Comment allez-vous?", "english": "How are you? (formal)"}, {"french": "Ça va?", "english": "How''s it going?"}]',
 'beginner', 'questions', 5, NOW());

-- ==============================================
-- STEP 6: INSERT LESSONS FROM MARKDOWN
-- ==============================================

INSERT INTO lessons (module_id, title, description, content, lesson_type, order_index, difficulty_level, estimated_time_minutes, is_active, created_at) VALUES
-- Module I: Greetings lessons (assuming module_id=1)
(1, 'Formal vs. Informal: vous and tu', 
 'Master the crucial distinction between formal and informal address in French - one of the most important concepts for proper social interaction.',
 '{"introduction": "Learn when to use vous vs tu", "key_concepts": ["formal situations with strangers and authority figures", "informal relationships with friends and family", "verb conjugation changes", "cultural implications"], "cultural_notes": ["When in doubt, use vous", "Wait to be invited to use tu", "Professional settings always use vous"], "practice_activities": ["Identify formal vs informal situations", "Choose correct pronoun", "Practice conjugations"]}', 
 'grammar', 1, 'beginner', 20, true, NOW()),

(1, 'Greetings Throughout the Day', 
 'Learn appropriate greetings for different times of day and various social situations.',
 '{"introduction": "Time-appropriate and situation-appropriate greetings", "vocabulary": ["bonjour", "bonsoir", "salut", "bonne nuit", "au revoir", "à bientôt"], "usage_rules": ["morning vs evening greetings", "formal vs informal contexts", "arrival vs departure"], "cultural_notes": ["Always greet when entering shops", "Bonjour is universal and safe", "Salut can mean both hi and bye"]}', 
 'vocabulary', 2, 'beginner', 15, true, NOW()),

(1, 'Introductions and Names', 
 'How to introduce yourself, ask for names, and respond when meeting people in French.',
 '{"introduction": "Personal introductions and meeting people", "key_phrases": ["Comment vous appelez-vous?", "Comment tu t''appelles?", "Je m''appelle", "Enchanté/Enchantée"], "grammar_focus": "Reflexive verbs with s''appeler", "cultural_notes": ["Always say enchanté when meeting someone", "Use correct gender form", "Shake hands when introduced"]}', 
 'conversation', 3, 'beginner', 20, true, NOW()),

(1, 'The Verb être (to be)', 
 'Master the fundamental irregular verb être - essential for describing yourself and others.',
 '{"introduction": "Essential verb conjugations for identity and description", "conjugations": ["je suis (I am)", "tu es (you are informal)", "il/elle est (he/she is)", "nous sommes (we are)", "vous êtes (you are formal/plural)", "ils/elles sont (they are)"], "usage": ["stating identity", "describing characteristics", "indicating location", "expressing temporary states"], "practice": ["conjugation drills", "sentence completion", "description exercises"]}', 
 'grammar', 4, 'beginner', 25, true, NOW()),

(1, 'Basic Courtesy and Politeness', 
 'Essential polite expressions and courtesy phrases for everyday interactions.',
 '{"introduction": "Fundamental politeness in French culture", "expressions": ["merci/merci beaucoup", "s''il vous plaît/s''il te plaît", "pardon/excusez-moi", "de rien/je vous en prie"], "cultural_importance": ["Politeness is crucial in French culture", "Always say please and thank you", "Acknowledge people when entering spaces"], "usage_contexts": ["shopping", "restaurants", "asking for help", "apologizing"]}',
 'conversation', 5, 'beginner', 18, true, NOW());

-- ==============================================
-- STEP 7: INSERT PRONUNCIATION WORDS FROM MARKDOWN
-- ==============================================

INSERT INTO pronunciation_words (french, english, pronunciation, example) VALUES
-- Core greetings with pronunciation from markdown
('bonjour', 'good day, hello', 'bon-zhoor', 'Bonjour, comment allez-vous?'),
('bonsoir', 'good evening', 'bon-swahr', 'Bonsoir madame Martin.'),
('salut', 'hi, bye (informal)', 'sa-loot', 'Salut, ça va?'),
('au revoir', 'goodbye', 'oh ruh-vwahr', 'Au revoir et à bientôt!'),
('à bientôt', 'see you soon', 'ah bee-an-toh', 'À bientôt mes amis!'),
('bonne nuit', 'good night', 'bun nwee', 'Bonne nuit et dormez bien.'),
('merci', 'thank you', 'mer-see', 'Merci beaucoup pour votre aide.'),
('ça va', 'how are you / I''m okay', 'sa va', 'Ça va bien, merci.'),

-- Formal vs informal pronouns with pronunciation
('vous', 'you (formal/plural)', 'voo', 'Comment vous appelez-vous?'),
('tu', 'you (informal)', 'tuu', 'Comment tu t''appelles?'),

-- Courtesy expressions with pronunciation
('s''il vous plaît', 'please (formal)', 'seel voo pleh', 'Un café, s''il vous plaît.'),
('s''il te plaît', 'please (informal)', 'seel tuh pleh', 'Aide-moi, s''il te plaît.'),
('pardon', 'excuse me, pardon', 'par-don', 'Pardon, où est la gare?'),
('excusez-moi', 'excuse me (formal)', 'ex-ku-zay mwah', 'Excusez-moi, pouvez-vous m''aider?'),

-- Introduction expressions with pronunciation
('enchanté', 'pleased to meet you (male)', 'on-shon-tay', 'Enchanté de vous rencontrer.'),
('enchantée', 'pleased to meet you (female)', 'on-shon-tay', 'Enchantée de faire votre connaissance.'),
('je m''appelle', 'my name is', 'zhuh ma-pell', 'Je m''appelle Marie Dubois.'),
('comment vous appelez-vous', 'what is your name (formal)', 'kom-mohn voo za-play voo', 'Comment vous appelez-vous, monsieur?'),
('comment tu t''appelles', 'what is your name (informal)', 'kom-mohn tuu ta-pell', 'Comment tu t''appelles?'),

-- Essential être conjugations with pronunciation
('je suis', 'I am', 'zhuh swee', 'Je suis français.'),
('tu es', 'you are (informal)', 'tuu eh', 'Tu es étudiant?'),
('il est', 'he is', 'eel eh', 'Il est professeur.'),
('elle est', 'she is', 'ell eh', 'Elle est médecin.'),
('nous sommes', 'we are', 'noo som', 'Nous sommes amis.'),
('vous êtes', 'you are (formal)', 'voo zet', 'Vous êtes le professeur.'),
('ils sont', 'they are (masculine)', 'eel son', 'Ils sont étudiants.'),
('elles sont', 'they are (feminine)', 'ell son', 'Elles sont françaises.'),

-- People and titles with pronunciation
('monsieur', 'sir, mister', 'muh-syur', 'Bonjour Monsieur Dupont.'),
('madame', 'madam, mrs', 'ma-dam', 'Bonsoir Madame Martin.'),
('mademoiselle', 'miss', 'mad-mwa-zel', 'Bonjour Mademoiselle Sophie.'),
('un ami', 'a friend (male)', 'un na-mee', 'Il est mon ami.'),
('une amie', 'a friend (female)', 'une na-mee', 'Elle est mon amie.'),
('un homme', 'a man', 'un ohm', 'Cet homme est très gentil.'),
('une femme', 'a woman', 'une fam', 'Cette femme est professeur.'),

-- Question words with pronunciation
('comment', 'how', 'kom-mohn', 'Comment ça va?'),
('où', 'where', 'oo', 'Où habitez-vous?'),
('quand', 'when', 'kohn', 'Quand arrivez-vous?'),
('pourquoi', 'why', 'poor-kwah', 'Pourquoi partez-vous?'),

-- Basic responses with pronunciation
('oui', 'yes', 'wee', 'Oui, c''est correct.'),
('non', 'no', 'non', 'Non, merci.'),
('de rien', 'you''re welcome', 'duh ree-ahn', 'De rien, c''est normal.'),
('je vous en prie', 'you''re welcome (formal)', 'zhuh voo zohn pree', 'Je vous en prie, monsieur.');

-- ==============================================
-- STEP 8: INSERT QUESTIONS FOR LESSONS
-- ==============================================

INSERT INTO questions (lesson_id, question_text, question_type, options, correct_answer, explanation, points, difficulty_level, order_index, created_at) VALUES
-- Lesson 1: Formal vs Informal questions (assuming lesson_id=1)
(1, 'When should you use "vous" instead of "tu"?', 'multiple_choice', 
 '["With close friends only", "With strangers or in formal situations", "Only with children", "Never, always use tu"]',
 'With strangers or in formal situations', 
 'Vous is used for formal situations, with strangers, older people, authority figures, and in professional settings. When in doubt, always use vous.', 
 10, 'beginner', 1, NOW()),

(1, 'Complete the formal question: "Comment ___ appelez-vous?"', 'fill_blank', 
 '["vous", "tu", "il", "elle"]',
 'vous', 
 'Use "vous" for the formal way to ask someone''s name. This shows respect and politeness.', 
 10, 'beginner', 2, NOW()),

(1, 'Which verb ending goes with "tu"?', 'multiple_choice',
 '["tu parlez", "tu parles", "tu parlons", "tu parlent"]',
 'tu parles',
 'With "tu", verbs typically end in -es (tu parles, tu es, tu vas)', 
 15, 'beginner', 3, NOW()),

-- Lesson 2: Greetings questions (assuming lesson_id=2)
(2, 'What is the appropriate greeting for the evening?', 'multiple_choice',
 '["Bonjour", "Salut", "Bonsoir", "Bonne nuit"]',
 'Bonsoir', 
 'Bonsoir is used to greet people in the evening, typically after 6 PM. Bonne nuit is only for bedtime.', 
 10, 'beginner', 1, NOW()),

(2, 'Which greeting can be used for both "hello" and "goodbye"?', 'multiple_choice',
 '["Bonjour", "Au revoir", "Salut", "Bonsoir"]',
 'Salut', 
 'Salut is informal and versatile - it can mean both "hi" and "bye" with people you know well.', 
 10, 'beginner', 2, NOW()),

(2, 'When do you say "Bonne nuit"?', 'multiple_choice',
 '["As an evening greeting", "When someone is going to bed", "Any time after 8 PM", "Instead of au revoir"]',
 'When someone is going to bed',
 'Bonne nuit is only used when you or someone else is actually going to sleep, not as a general evening greeting.',
 15, 'beginner', 3, NOW()),

-- Lesson 3: Introductions questions (assuming lesson_id=3)
(3, 'How do you say "My name is..." in French?', 'multiple_choice',
 '["Mon nom est", "Je m''appelle", "Je suis nom", "Ma nom c''est"]',
 'Je m''appelle', 
 'Je m''appelle is the standard way to introduce your name using the reflexive verb s''appeler.', 
 15, 'beginner', 1, NOW()),

(3, 'What do you say when meeting someone for the first time (if you''re male)?', 'multiple_choice',
 '["Bonjour", "Salut", "Enchanté", "Merci"]',
 'Enchanté', 
 'Enchanté means "pleased to meet you" and is said by males. Females say "Enchantée".', 
 10, 'beginner', 2, NOW()),

(3, 'How do you ask "What is your name?" informally?', 'multiple_choice',
 '["Comment vous appelez-vous?", "Comment tu t''appelles?", "Quel est ton nom?", "Tu es qui?"]',
 'Comment tu t''appelles?',
 'Use "Comment tu t''appelles?" for informal situations with friends, family, or people your age.',
 15, 'beginner', 3, NOW()),

-- Lesson 4: Être verb questions (assuming lesson_id=4)
(4, 'Complete: "Je ___ français" (I am French)', 'fill_blank',
 '["suis", "es", "est", "êtes"]',
 'suis', 
 'Je suis is the correct conjugation of être with "je". Remember: je suis, tu es, il/elle est.', 
 15, 'beginner', 1, NOW()),

(4, 'What is the correct form: "Vous ___ le professeur"', 'fill_blank',
 '["suis", "es", "est", "êtes"]',
 'êtes', 
 'Vous êtes is the correct conjugation of être with "vous" (formal or plural you).', 
 15, 'beginner', 2, NOW()),

(4, 'Choose the correct translation: "They are students" (masculine)', 'multiple_choice',
 '["Ils sont étudiants", "Elles sont étudiantes", "Vous êtes étudiants", "Nous sommes étudiants"]',
 'Ils sont étudiants',
 'For masculine "they", use "ils sont". The adjective "étudiants" agrees with the masculine plural subject.',
 20, 'beginner', 3, NOW()),

-- Lesson 5: Courtesy questions (assuming lesson_id=5)
(5, 'How do you say "please" formally?', 'multiple_choice',
 '["s''il te plaît", "s''il vous plaît", "merci", "pardon"]',
 's''il vous plaît',
 'S''il vous plaît is the formal way to say please. Use s''il te plaît informally.',
 10, 'beginner', 1, NOW()),

(5, 'What is the most common response to "merci"?', 'multiple_choice',
 '["oui", "non", "de rien", "bonjour"]',
 'de rien',
 'De rien means "you''re welcome" or literally "it''s nothing". You can also say "je vous en prie" formally.',
 10, 'beginner', 2, NOW());

-- ==============================================
-- STEP 9: LINK VOCABULARY TO LESSONS
-- ==============================================

-- Get the vocabulary IDs for linking (we'll use the french_word to find IDs)
DO $$
DECLARE
    lesson1_id INTEGER;
    lesson2_id INTEGER; 
    lesson3_id INTEGER;
    lesson4_id INTEGER;
    lesson5_id INTEGER;
BEGIN
    -- Get lesson IDs
    SELECT id INTO lesson1_id FROM lessons WHERE title = 'Formal vs. Informal: vous and tu';
    SELECT id INTO lesson2_id FROM lessons WHERE title = 'Greetings Throughout the Day';
    SELECT id INTO lesson3_id FROM lessons WHERE title = 'Introductions and Names';
    SELECT id INTO lesson4_id FROM lessons WHERE title = 'The Verb être (to be)';
    SELECT id INTO lesson5_id FROM lessons WHERE title = 'Basic Courtesy and Politeness';

    -- Link vocabulary to lessons
    -- Lesson 1: Formal vs Informal
    INSERT INTO lesson_vocabulary (lesson_id, vocabulary_id, is_primary)
    SELECT lesson1_id, id, true FROM vocabulary WHERE french_word IN ('vous', 'tu', 'vous êtes', 'tu es');

    -- Lesson 2: Greetings
    INSERT INTO lesson_vocabulary (lesson_id, vocabulary_id, is_primary)
    SELECT lesson2_id, id, true FROM vocabulary WHERE french_word IN ('bonjour', 'salut', 'bonsoir', 'bonne nuit', 'au revoir', 'à bientôt', 'ça va');

    -- Lesson 3: Introductions
    INSERT INTO lesson_vocabulary (lesson_id, vocabulary_id, is_primary)
    SELECT lesson3_id, id, true FROM vocabulary WHERE french_word IN ('enchanté', 'enchantée', 'monsieur', 'madame', 'un ami', 'une amie', 'comment');

    -- Lesson 4: Être verb
    INSERT INTO lesson_vocabulary (lesson_id, vocabulary_id, is_primary)
    SELECT lesson4_id, id, true FROM vocabulary WHERE french_word IN ('je suis', 'tu es', 'il est', 'elle est', 'nous sommes', 'vous êtes', 'ils sont', 'elles sont');

    -- Lesson 5: Courtesy
    INSERT INTO lesson_vocabulary (lesson_id, vocabulary_id, is_primary)
    SELECT lesson5_id, id, true FROM vocabulary WHERE french_word IN ('merci', 's''il vous plaît', 's''il te plaît', 'pardon', 'excusez-moi', 'oui', 'non');

END $$;

-- ==============================================
-- STEP 10: LINK GRAMMAR TO LESSONS
-- ==============================================

DO $$
DECLARE
    lesson1_id INTEGER;
    lesson2_id INTEGER;
    lesson3_id INTEGER; 
    lesson4_id INTEGER;
    lesson5_id INTEGER;
    grammar1_id INTEGER;
    grammar2_id INTEGER;
    grammar3_id INTEGER;
    grammar4_id INTEGER;
    grammar5_id INTEGER;
BEGIN
    -- Get lesson IDs
    SELECT id INTO lesson1_id FROM lessons WHERE title = 'Formal vs. Informal: vous and tu';
    SELECT id INTO lesson2_id FROM lessons WHERE title = 'Greetings Throughout the Day';
    SELECT id INTO lesson3_id FROM lessons WHERE title = 'Introductions and Names';
    SELECT id INTO lesson4_id FROM lessons WHERE title = 'The Verb être (to be)';
    SELECT id INTO lesson5_id FROM lessons WHERE title = 'Basic Courtesy and Politeness';

    -- Get grammar rule IDs
    SELECT id INTO grammar1_id FROM grammar_rules WHERE title = 'Formal vs. Informal: vous and tu';
    SELECT id INTO grammar2_id FROM grammar_rules WHERE title = 'The Verb être (to be)';
    SELECT id INTO grammar3_id FROM grammar_rules WHERE title = 'Reflexive Verb s''appeler (to be called)';
    SELECT id INTO grammar4_id FROM grammar_rules WHERE title = 'Greetings Throughout the Day';
    SELECT id INTO grammar5_id FROM grammar_rules WHERE title = 'Basic Question Formation';

    -- Link grammar rules to lessons
    INSERT INTO lesson_grammar (lesson_id, grammar_rule_id, is_primary) VALUES
    (lesson1_id, grammar1_id, true),   -- Formal vs Informal lesson -> Formal vs Informal grammar
    (lesson2_id, grammar4_id, true),   -- Greetings lesson -> Greetings grammar  
    (lesson3_id, grammar3_id, true),   -- Introductions lesson -> s'appeler grammar
    (lesson4_id, grammar2_id, true),   -- Être lesson -> Être grammar
    (lesson5_id, grammar5_id, false);  -- Courtesy lesson -> Question formation (secondary)

END $$;

-- ==============================================
-- VERIFICATION AND SUMMARY
-- ==============================================

-- Display summary of inserted content
SELECT '=== CONTENT UPLOAD SUMMARY ===' as status;
SELECT 'Modules created: ' || COUNT(*)::text as summary FROM modules;
SELECT 'Vocabulary items: ' || COUNT(*)::text as summary FROM vocabulary;
SELECT 'Grammar rules: ' || COUNT(*)::text as summary FROM grammar_rules;
SELECT 'Lessons created: ' || COUNT(*)::text as summary FROM lessons;
SELECT 'Pronunciation words: ' || COUNT(*)::text as summary FROM pronunciation_words;
SELECT 'Questions created: ' || COUNT(*)::text as summary FROM questions;
SELECT 'Lesson-vocabulary links: ' || COUNT(*)::text as summary FROM lesson_vocabulary;
SELECT 'Lesson-grammar links: ' || COUNT(*)::text as summary FROM lesson_grammar;

-- Check specific content
SELECT '=== MODULE DETAILS ===' as status;
SELECT title, description FROM modules ORDER BY order_index;

SELECT '=== LESSON DETAILS ===' as status;
SELECT l.title, m.title as module_title, l.difficulty_level, l.estimated_time_minutes 
FROM lessons l 
JOIN modules m ON l.module_id = m.id 
ORDER BY m.order_index, l.order_index;

SELECT '✅ SUCCESS: French learning content from markdown has been uploaded!' as final_message;
SELECT '📚 Content includes: Greetings, Formal/Informal usage, Introductions, Être verb, and Courtesy expressions' as content_summary;
SELECT '🔊 ' || COUNT(*) || ' pronunciation words added for proper French pronunciation' as pronunciation_summary FROM pronunciation_words;
